DROP TEMPORARY TABLE IF EXISTS NEW_CUSTOMERS;
CREATE TEMPORARY TABLE NEW_CUSTOMERS

SELECT
		CUSTOMER_ID AS CUSTOMER_ID,
		MIN(LEFT(DATE_ID,7)) AS CUSTOMER_ACQ
FROM
		SALES
GROUP BY
		customer_ID
;		
SELECT
		CUSTOMER_ACQ AS 'CUSTOMER AQCUSITION DATE',
		COUNT(CUSTOMER_ACQ) AS 'NUMBER OF CUSTOMERS'
FROM NEW_CUSTOMERS
GROUP BY
	CUSTOMER_ACQ